USE `auth`;

START TRANSACTION;

-- Change this to the target Battle.net account ID
SET @BNET_ID := 1;

-- Full unlock mask (UINT32 max)
SET @MASK := 4294967295;

INSERT INTO `battlenet_item_appearances` (`battlenetAccountId`, `blobIndex`, `appearanceMask`)
SELECT @BNET_ID, nums.n, @MASK
FROM (
    SELECT
        o.d + 10*t.d + 100*h.d + 1000*th.d AS n
    FROM (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
          UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) o
    CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
                UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t
    CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
                UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) h
    CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
                UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) th
) AS nums
WHERE nums.n BETWEEN 0 AND 9999
ON DUPLICATE KEY UPDATE
  `appearanceMask` = @MASK;

COMMIT;
