-- SmartAI Fix: Non-existent creature, spell, quest, and text references
-- Auto-generated from DBErrors.log parsing
-- Total errors addressed: ~1,610

-- ============================================================
-- 1. Delete smart_scripts rows referencing non-existent spells.
--    625 unique rows identified from error log.
--    Covers action_type 11 (CAST), event spellHit, victim_casting, etc.
-- ============================================================

DELETE FROM smart_scripts WHERE entryorguid = -251442 AND source_type = 0 AND id IN (5);
DELETE FROM smart_scripts WHERE entryorguid = -251439 AND source_type = 0 AND id IN (5);
DELETE FROM smart_scripts WHERE entryorguid = -251437 AND source_type = 0 AND id IN (5);
DELETE FROM smart_scripts WHERE entryorguid = -251436 AND source_type = 0 AND id IN (5);
DELETE FROM smart_scripts WHERE entryorguid = -251430 AND source_type = 0 AND id IN (5);
DELETE FROM smart_scripts WHERE entryorguid = -251426 AND source_type = 0 AND id IN (5);
DELETE FROM smart_scripts WHERE entryorguid = -251425 AND source_type = 0 AND id IN (5);
DELETE FROM smart_scripts WHERE entryorguid = 437 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 503 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 568 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 683 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 736 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 787 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 819 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 909 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 938 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 940 AND source_type = 0 AND id IN (0, 1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 942 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 1028 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 1029 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 1036 AND source_type = 0 AND id IN (1, 3);
DELETE FROM smart_scripts WHERE entryorguid = 1038 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 1046 AND source_type = 0 AND id IN (0, 2, 3);
DELETE FROM smart_scripts WHERE entryorguid = 1060 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 1062 AND source_type = 0 AND id IN (0, 1);
DELETE FROM smart_scripts WHERE entryorguid = 1175 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 1183 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 1364 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 1540 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 1544 AND source_type = 0 AND id IN (2, 3);
DELETE FROM smart_scripts WHERE entryorguid = 1563 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 1679 AND source_type = 0 AND id IN (0, 1);
DELETE FROM smart_scripts WHERE entryorguid = 1717 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 1789 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 1794 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 1854 AND source_type = 0 AND id IN (1, 4);
DELETE FROM smart_scripts WHERE entryorguid = 1911 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 2021 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 2030 AND source_type = 0 AND id IN (0, 1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 2170 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 2171 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 2203 AND source_type = 0 AND id IN (0, 1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 2205 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 2254 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 2338 AND source_type = 0 AND id IN (1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 2344 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 2417 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 2422 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 2581 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 2583 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 2584 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 2605 AND source_type = 0 AND id IN (4);
DELETE FROM smart_scripts WHERE entryorguid = 2640 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 2651 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 2713 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 2718 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 2742 AND source_type = 0 AND id IN (0, 1);
DELETE FROM smart_scripts WHERE entryorguid = 2744 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 2761 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 3271 AND source_type = 0 AND id IN (2, 3);
DELETE FROM smart_scripts WHERE entryorguid = 3380 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 3385 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 3458 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 3672 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 3804 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 3808 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 3811 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 3840 AND source_type = 0 AND id IN (5);
DELETE FROM smart_scripts WHERE entryorguid = 3939 AND source_type = 0 AND id IN (0, 1);
DELETE FROM smart_scripts WHERE entryorguid = 3940 AND source_type = 0 AND id IN (0, 1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 4016 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 4025 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 4036 AND source_type = 0 AND id IN (0, 1);
DELETE FROM smart_scripts WHERE entryorguid = 4050 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4051 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4116 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4119 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 4151 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 4289 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4296 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4299 AND source_type = 0 AND id IN (0, 1);
DELETE FROM smart_scripts WHERE entryorguid = 4300 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4303 AND source_type = 0 AND id IN (2, 3);
DELETE FROM smart_scripts WHERE entryorguid = 4306 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4328 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 4334 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 4467 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 4481 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4506 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4515 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 4517 AND source_type = 0 AND id IN (0, 2);
DELETE FROM smart_scripts WHERE entryorguid = 4649 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4680 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 4682 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 4684 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 4799 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4805 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 4809 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 4818 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4820 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 4831 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 4845 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 4847 AND source_type = 0 AND id IN (0, 2);
DELETE FROM smart_scripts WHERE entryorguid = 4848 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 4852 AND source_type = 0 AND id IN (0, 1);
DELETE FROM smart_scripts WHERE entryorguid = 4962 AND source_type = 0 AND id IN (0, 3);
DELETE FROM smart_scripts WHERE entryorguid = 4971 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 5236 AND source_type = 0 AND id IN (1, 2, 3, 4);
DELETE FROM smart_scripts WHERE entryorguid = 5333 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 5335 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 5601 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 5648 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 5682 AND source_type = 0 AND id IN (0, 1);
DELETE FROM smart_scripts WHERE entryorguid = 5715 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 5771 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 5808 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 5862 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 5874 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 5915 AND source_type = 0 AND id IN (4);
DELETE FROM smart_scripts WHERE entryorguid = 6113 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 6194 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 6207 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 6210 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 6226 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 6584 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 7111 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 7175 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 7291 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 7321 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 7372 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 7428 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 7606 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 7666 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 7727 AND source_type = 0 AND id IN (0, 1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 7789 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 7843 AND source_type = 0 AND id IN (4);
DELETE FROM smart_scripts WHERE entryorguid = 7858 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 8527 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 8535 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 8546 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 8900 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 8904 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 8909 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 8910 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 8912 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 8913 AND source_type = 0 AND id IN (7);
DELETE FROM smart_scripts WHERE entryorguid = 9029 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 9045 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 9217 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 9261 AND source_type = 0 AND id IN (4);
DELETE FROM smart_scripts WHERE entryorguid = 9262 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 9397 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 9442 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 9451 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 9517 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 9693 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 9860 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 10081 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 10390 AND source_type = 0 AND id IN (1, 4);
DELETE FROM smart_scripts WHERE entryorguid = 10393 AND source_type = 0 AND id IN (1, 3);
DELETE FROM smart_scripts WHERE entryorguid = 10422 AND source_type = 0 AND id IN (2, 4);
DELETE FROM smart_scripts WHERE entryorguid = 10425 AND source_type = 0 AND id IN (0, 2);
DELETE FROM smart_scripts WHERE entryorguid = 10426 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 10472 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 10477 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 10696 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 10824 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 10979 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 11032 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 11257 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 11383 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 11444 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 11459 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 11462 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 11471 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 11484 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 11492 AND source_type = 0 AND id IN (10);
DELETE FROM smart_scripts WHERE entryorguid = 11622 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 11682 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 11838 AND source_type = 0 AND id IN (0, 10000);
DELETE FROM smart_scripts WHERE entryorguid = 12320 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 12378 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 12396 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 13096 AND source_type = 0 AND id IN (1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 13099 AND source_type = 0 AND id IN (1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 13197 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 13219 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 13443 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 13540 AND source_type = 0 AND id IN (1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 13541 AND source_type = 0 AND id IN (1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 13542 AND source_type = 0 AND id IN (1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 13546 AND source_type = 0 AND id IN (1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 13547 AND source_type = 0 AND id IN (1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 13548 AND source_type = 0 AND id IN (1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 14303 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 14354 AND source_type = 0 AND id IN (20);
DELETE FROM smart_scripts WHERE entryorguid = 14832 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 15184 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 15273 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 15274 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 15277 AND source_type = 0 AND id IN (6);
DELETE FROM smart_scripts WHERE entryorguid = 15537 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 15648 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 15966 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 16184 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 16331 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 16348 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 16378 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 16521 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 16523 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 17143 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 17150 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 17199 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 17206 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 17304 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 17309 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 17395 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 17477 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 17540 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 17551 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 17662 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 17669 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 17694 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 17723 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 17724 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 17725 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 17729 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 17765 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 17766 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 17771 AND source_type = 0 AND id IN (6);
DELETE FROM smart_scripts WHERE entryorguid = 17810 AND source_type = 0 AND id IN (6);
DELETE FROM smart_scripts WHERE entryorguid = 17871 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 17892 AND source_type = 0 AND id IN (20, 22);
DELETE FROM smart_scripts WHERE entryorguid = 17938 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 18105 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 18309 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 18312 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 18315 AND source_type = 0 AND id IN (2, 3, 4);
DELETE FROM smart_scripts WHERE entryorguid = 18331 AND source_type = 0 AND id IN (3, 4, 5);
DELETE FROM smart_scripts WHERE entryorguid = 18634 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 18637 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 18685 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 18794 AND source_type = 0 AND id IN (15);
DELETE FROM smart_scripts WHERE entryorguid = 18994 AND source_type = 0 AND id IN (5);
DELETE FROM smart_scripts WHERE entryorguid = 19016 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 19191 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 19306 AND source_type = 0 AND id IN (0, 1);
DELETE FROM smart_scripts WHERE entryorguid = 19354 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 19413 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 19480 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 19671 AND source_type = 0 AND id IN (4);
DELETE FROM smart_scripts WHERE entryorguid = 21338 AND source_type = 0 AND id IN (10);
DELETE FROM smart_scripts WHERE entryorguid = 22006 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 23188 AND source_type = 0 AND id IN (7);
DELETE FROM smart_scripts WHERE entryorguid = 23368 AND source_type = 0 AND id IN (1, 2);
DELETE FROM smart_scripts WHERE entryorguid = 23619 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 23623 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 23624 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 23625 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 23626 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 23637 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 24613 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 24614 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 24687 AND source_type = 0 AND id IN (4, 5);
DELETE FROM smart_scripts WHERE entryorguid = 24882 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 25087 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 25090 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 25091 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 25092 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 25420 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 25452 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 26178 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 26428 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 27727 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 27731 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 28200 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 28490 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 29129 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 29614 AND source_type = 0 AND id IN (5, 6, 7);
DELETE FROM smart_scripts WHERE entryorguid = 29885 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 30180 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 30409 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 30475 AND source_type = 0 AND id IN (7);
DELETE FROM smart_scripts WHERE entryorguid = 30665 AND source_type = 0 AND id IN (6);
DELETE FROM smart_scripts WHERE entryorguid = 30829 AND source_type = 0 AND id IN (4);
DELETE FROM smart_scripts WHERE entryorguid = 31779 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 32263 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 32279 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 32300 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 32377 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 35143 AND source_type = 0 AND id IN (1, 3);
DELETE FROM smart_scripts WHERE entryorguid = 35454 AND source_type = 0 AND id IN (0, 3);
DELETE FROM smart_scripts WHERE entryorguid = 36412 AND source_type = 0 AND id IN (0, 3);
DELETE FROM smart_scripts WHERE entryorguid = 36441 AND source_type = 0 AND id IN (0, 3);
DELETE FROM smart_scripts WHERE entryorguid = 36442 AND source_type = 0 AND id IN (0, 3);
DELETE FROM smart_scripts WHERE entryorguid = 36446 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 36499 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 36516 AND source_type = 0 AND id IN (5);
DELETE FROM smart_scripts WHERE entryorguid = 36522 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 36551 AND source_type = 0 AND id IN (5);
DELETE FROM smart_scripts WHERE entryorguid = 36564 AND source_type = 0 AND id IN (3, 5);
DELETE FROM smart_scripts WHERE entryorguid = 36620 AND source_type = 0 AND id IN (3, 5, 7);
DELETE FROM smart_scripts WHERE entryorguid = 36688 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 36816 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 36840 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 36842 AND source_type = 0 AND id IN (1, 3);
DELETE FROM smart_scripts WHERE entryorguid = 36879 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 36892 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 36896 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 37161 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 37712 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 37728 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 38033 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 38482 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 38926 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 39638 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 39732 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 39800 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 39958 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 40417 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 40419 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 40882 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 41082 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 41158 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 41311 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 41407 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 41466 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 41935 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 43451 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 43540 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 43605 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 43636 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 43726 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 43778 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 44317 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 44614 AND source_type = 0 AND id IN (6);
DELETE FROM smart_scripts WHERE entryorguid = 44794 AND source_type = 0 AND id IN (6);
DELETE FROM smart_scripts WHERE entryorguid = 45031 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 45692 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 46164 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 47060 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 47138 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 47438 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 47583 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 47739 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 48312 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 48923 AND source_type = 0 AND id IN (3);
DELETE FROM smart_scripts WHERE entryorguid = 49148 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 49263 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 50051 AND source_type = 0 AND id IN (1);
DELETE FROM smart_scripts WHERE entryorguid = 51792 AND source_type = 0 AND id IN (2);
DELETE FROM smart_scripts WHERE entryorguid = 52214 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 54324 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 60410 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 62732 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 70401 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 88780 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 93127 AND source_type = 0 AND id IN (13);
DELETE FROM smart_scripts WHERE entryorguid = 96545 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 111122 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 142732 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 150856 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 178165 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 179388 AND source_type = 0 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 181364 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 181427 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 181775 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 184853 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 185272 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 185589 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 185814 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186103 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186438 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186509 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186512 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186528 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186535 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186582 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186605 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186606 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186724 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186736 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186783 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 186962 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187060 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187071 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187096 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187102 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187107 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187108 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187201 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187299 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187353 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187478 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187552 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187612 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187614 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187750 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187842 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187867 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187868 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187938 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 187960 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 188098 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 188413 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 188444 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 188667 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 188687 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 188691 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 188711 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 188755 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 189206 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 189220 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 189337 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 189468 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 189489 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 189654 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 189757 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 189768 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 189871 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 189872 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190144 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190171 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190244 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190480 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190538 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190641 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190654 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190719 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190765 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190776 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190779 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190906 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190916 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190953 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 190997 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191039 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191057 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191136 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191145 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191378 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191403 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191536 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191663 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191687 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191696 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191826 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191843 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191902 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 191917 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 192146 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 192223 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 192224 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 192237 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 192470 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 192597 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 192626 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 192652 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 192694 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 192744 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193083 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193142 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193179 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193231 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193232 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193385 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193395 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193407 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193514 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193541 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193598 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193652 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193663 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193676 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193686 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193691 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193949 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 193969 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194078 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194095 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194144 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194179 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194306 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194351 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194522 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194588 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194666 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194684 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194880 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 194966 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 195062 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 195064 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 195187 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 195195 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 195261 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 195330 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 195552 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 195717 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 195761 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 195846 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 195969 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196096 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196168 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196176 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196322 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196336 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196377 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196442 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196587 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196624 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196634 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196646 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196663 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196680 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196767 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196770 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196826 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 196927 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 197131 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 197133 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 197220 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 197260 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 197352 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 197665 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 197702 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 197732 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 197815 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 197914 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 198023 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 198343 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 198651 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 198779 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 198813 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 198905 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 199195 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 199197 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 199401 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 200066 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 200138 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 200286 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 200321 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 200589 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 200593 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 200740 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 200758 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 201549 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 201677 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 201794 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 201820 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 201822 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 202683 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 203754 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 203757 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 203948 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 204072 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 204099 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 205061 AND source_type = 0 AND id IN (10000);
DELETE FROM smart_scripts WHERE entryorguid = 2732801 AND source_type = 9 AND id IN (3, 4);
DELETE FROM smart_scripts WHERE entryorguid = 2968400 AND source_type = 9 AND id IN (0);
DELETE FROM smart_scripts WHERE entryorguid = 14971802 AND source_type = 9 AND id IN (1);

-- ============================================================
-- 2. Delete smart_scripts rows referencing non-existent creatures.
--    12 unique rows.
-- ============================================================

DELETE FROM smart_scripts WHERE entryorguid = 7748 AND source_type = 2 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 123053 AND source_type = 0 AND id = 102;
DELETE FROM smart_scripts WHERE entryorguid = 188247 AND source_type = 0 AND id = 101;
DELETE FROM smart_scripts WHERE entryorguid = 190543 AND source_type = 0 AND id = 102;
DELETE FROM smart_scripts WHERE entryorguid = 199772 AND source_type = 0 AND id = 101;
DELETE FROM smart_scripts WHERE entryorguid = 217088 AND source_type = 0 AND id = 102;
DELETE FROM smart_scripts WHERE entryorguid = 235405 AND source_type = 0 AND id = 102;
DELETE FROM smart_scripts WHERE entryorguid = 910714 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9106686 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9106798 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9106915 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9107399 AND source_type = 12 AND id = 3;

-- ============================================================
-- 3. Delete smart_scripts rows referencing non-existent quests.
--    6 unique rows.
-- ============================================================

DELETE FROM smart_scripts WHERE entryorguid = 96686 AND source_type = 0 AND id = 12;
DELETE FROM smart_scripts WHERE entryorguid = 139522 AND source_type = 0 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 139522 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 139522 AND source_type = 0 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9106760 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9106978 AND source_type = 12 AND id = 3;

-- ============================================================
-- 4. Delete smart_scripts rows referencing non-existent creature_text.
--    75 unique rows.
-- ============================================================

DELETE FROM smart_scripts WHERE entryorguid = -121192 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = -84615 AND source_type = 0 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 6172 AND source_type = 0 AND id = 4;
DELETE FROM smart_scripts WHERE entryorguid = 6177 AND source_type = 0 AND id = 4;
DELETE FROM smart_scripts WHERE entryorguid = 7917 AND source_type = 0 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 7917 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 26445 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 26445 AND source_type = 0 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 26445 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 26678 AND source_type = 0 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 29919 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 30483 AND source_type = 0 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 30484 AND source_type = 0 AND id = 6;
DELETE FROM smart_scripts WHERE entryorguid = 32331 AND source_type = 0 AND id = 4;
DELETE FROM smart_scripts WHERE entryorguid = 32331 AND source_type = 0 AND id = 5;
DELETE FROM smart_scripts WHERE entryorguid = 32331 AND source_type = 0 AND id = 6;
DELETE FROM smart_scripts WHERE entryorguid = 32331 AND source_type = 0 AND id = 7;
DELETE FROM smart_scripts WHERE entryorguid = 32331 AND source_type = 0 AND id = 8;
DELETE FROM smart_scripts WHERE entryorguid = 32331 AND source_type = 0 AND id = 9;
DELETE FROM smart_scripts WHERE entryorguid = 32331 AND source_type = 0 AND id = 10;
DELETE FROM smart_scripts WHERE entryorguid = 32331 AND source_type = 0 AND id = 11;
DELETE FROM smart_scripts WHERE entryorguid = 32331 AND source_type = 0 AND id = 12;
DELETE FROM smart_scripts WHERE entryorguid = 32331 AND source_type = 0 AND id = 13;
DELETE FROM smart_scripts WHERE entryorguid = 34007 AND source_type = 0 AND id = 14;
DELETE FROM smart_scripts WHERE entryorguid = 55918 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 93127 AND source_type = 0 AND id = 14;
DELETE FROM smart_scripts WHERE entryorguid = 93967 AND source_type = 0 AND id = 13;
DELETE FROM smart_scripts WHERE entryorguid = 96979 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 96979 AND source_type = 0 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 101055 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 165107 AND source_type = 0 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 165107 AND source_type = 0 AND id = 4;
DELETE FROM smart_scripts WHERE entryorguid = 166227 AND source_type = 0 AND id = 4;
DELETE FROM smart_scripts WHERE entryorguid = 166227 AND source_type = 0 AND id = 5;
DELETE FROM smart_scripts WHERE entryorguid = 166227 AND source_type = 0 AND id = 6;
DELETE FROM smart_scripts WHERE entryorguid = 166227 AND source_type = 0 AND id = 7;
DELETE FROM smart_scripts WHERE entryorguid = 167424 AND source_type = 0 AND id = 5;
DELETE FROM smart_scripts WHERE entryorguid = 170179 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 181198 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 187700 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 188601 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 188601 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 189065 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 189089 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 189226 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 192674 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 192674 AND source_type = 0 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 192674 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 192674 AND source_type = 0 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 192674 AND source_type = 0 AND id = 4;
DELETE FROM smart_scripts WHERE entryorguid = 192674 AND source_type = 0 AND id = 5;
DELETE FROM smart_scripts WHERE entryorguid = 192674 AND source_type = 0 AND id = 6;
DELETE FROM smart_scripts WHERE entryorguid = 192674 AND source_type = 0 AND id = 7;
DELETE FROM smart_scripts WHERE entryorguid = 192674 AND source_type = 0 AND id = 9;
DELETE FROM smart_scripts WHERE entryorguid = 192674 AND source_type = 0 AND id = 10;
DELETE FROM smart_scripts WHERE entryorguid = 193991 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 193995 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 194076 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 194076 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 194076 AND source_type = 0 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 194136 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 194136 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 194327 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 194394 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 202571 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 206428 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 206455 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 206468 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 206527 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 206530 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 206571 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 207160 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 208907 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 214538 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 215158 AND source_type = 0 AND id = 0;

-- ============================================================
-- 5. Delete smart_scripts rows with invalid creature entry for target guid.
--    83 unique rows.
-- ============================================================

DELETE FROM smart_scripts WHERE entryorguid = -202373 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = -202371 AND source_type = 0 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = -85118 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = -85098 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 3626 AND source_type = 2 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 3626 AND source_type = 2 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 3626 AND source_type = 2 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 3626 AND source_type = 2 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 3626 AND source_type = 2 AND id = 4;
DELETE FROM smart_scripts WHERE entryorguid = 3626 AND source_type = 2 AND id = 5;
DELETE FROM smart_scripts WHERE entryorguid = 4498 AND source_type = 2 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 4498 AND source_type = 2 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 4498 AND source_type = 2 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 4498 AND source_type = 2 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 4498 AND source_type = 2 AND id = 4;
DELETE FROM smart_scripts WHERE entryorguid = 16514 AND source_type = 0 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 16514 AND source_type = 0 AND id = 5;
DELETE FROM smart_scripts WHERE entryorguid = 17320 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 17321 AND source_type = 0 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 25258 AND source_type = 0 AND id = 7;
DELETE FROM smart_scripts WHERE entryorguid = 25258 AND source_type = 0 AND id = 8;
DELETE FROM smart_scripts WHERE entryorguid = 26073 AND source_type = 0 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 26073 AND source_type = 0 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 26073 AND source_type = 0 AND id = 4;
DELETE FROM smart_scripts WHERE entryorguid = 26073 AND source_type = 0 AND id = 5;
DELETE FROM smart_scripts WHERE entryorguid = 33707 AND source_type = 0 AND id = 9;
DELETE FROM smart_scripts WHERE entryorguid = 33785 AND source_type = 0 AND id = 6;
DELETE FROM smart_scripts WHERE entryorguid = 33785 AND source_type = 0 AND id = 8;
DELETE FROM smart_scripts WHERE entryorguid = 176551 AND source_type = 0 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 181045 AND source_type = 1 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 181051 AND source_type = 1 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 910067 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910074 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910099 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910126 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910168 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910269 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910273 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910669 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 1967600 AND source_type = 9 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 1967600 AND source_type = 9 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 1967600 AND source_type = 9 AND id = 4;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 8;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 9;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 10;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 18;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 19;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 25;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 34;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 35;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 43;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 44;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 54;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 60;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 63;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 64;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 65;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 66;
DELETE FROM smart_scripts WHERE entryorguid = 2034500 AND source_type = 9 AND id = 67;
DELETE FROM smart_scripts WHERE entryorguid = 2525800 AND source_type = 9 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 2525801 AND source_type = 9 AND id = 7;
DELETE FROM smart_scripts WHERE entryorguid = 2525801 AND source_type = 9 AND id = 8;
DELETE FROM smart_scripts WHERE entryorguid = 2525801 AND source_type = 9 AND id = 9;
DELETE FROM smart_scripts WHERE entryorguid = 2525801 AND source_type = 9 AND id = 10;
DELETE FROM smart_scripts WHERE entryorguid = 2525801 AND source_type = 9 AND id = 12;
DELETE FROM smart_scripts WHERE entryorguid = 2525801 AND source_type = 9 AND id = 13;
DELETE FROM smart_scripts WHERE entryorguid = 2525801 AND source_type = 9 AND id = 15;
DELETE FROM smart_scripts WHERE entryorguid = 2525801 AND source_type = 9 AND id = 16;
DELETE FROM smart_scripts WHERE entryorguid = 2525801 AND source_type = 9 AND id = 18;
DELETE FROM smart_scripts WHERE entryorguid = 2525801 AND source_type = 9 AND id = 19;
DELETE FROM smart_scripts WHERE entryorguid = 2525802 AND source_type = 9 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 2525802 AND source_type = 9 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 2525802 AND source_type = 9 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 2525802 AND source_type = 9 AND id = 5;
DELETE FROM smart_scripts WHERE entryorguid = 2525802 AND source_type = 9 AND id = 6;
DELETE FROM smart_scripts WHERE entryorguid = 2525802 AND source_type = 9 AND id = 8;
DELETE FROM smart_scripts WHERE entryorguid = 2525802 AND source_type = 9 AND id = 9;
DELETE FROM smart_scripts WHERE entryorguid = 2525803 AND source_type = 9 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 2525803 AND source_type = 9 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 9105589 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9991400 AND source_type = 9 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9991400 AND source_type = 9 AND id = 4;
DELETE FROM smart_scripts WHERE entryorguid = 9991400 AND source_type = 9 AND id = 5;

-- ============================================================
-- 6. Delete smart_scripts rows with invalid creature guid as target.
--    48 unique rows.
-- ============================================================

DELETE FROM smart_scripts WHERE entryorguid = 23899 AND source_type = 0 AND id = 6;
DELETE FROM smart_scripts WHERE entryorguid = 94410 AND source_type = 0 AND id = 1;
DELETE FROM smart_scripts WHERE entryorguid = 188246 AND source_type = 0 AND id = 2;
DELETE FROM smart_scripts WHERE entryorguid = 910001 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910026 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910065 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910070 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910081 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910095 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910096 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910104 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910115 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910116 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910117 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910118 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910119 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910131 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910138 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910146 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910147 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910150 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910160 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910164 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910183 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910279 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910301 AND source_type = 12 AND id = 0;
DELETE FROM smart_scripts WHERE entryorguid = 910459 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 910682 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 910686 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 910687 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 910688 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 910692 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 910696 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 910697 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 910698 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 910716 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 910728 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9105566 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9105567 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9105568 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9105569 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9105570 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9105571 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9105653 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9105664 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9105724 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9105725 AND source_type = 12 AND id = 3;
DELETE FROM smart_scripts WHERE entryorguid = 9105755 AND source_type = 12 AND id = 3;

