-- ============================================================
-- Spell: Windrunner's Grace (ID: 1900003)
-- Generated by VoxCore Spell Creator
-- ============================================================

-- spell_name
REPLACE INTO `hotfixes`.`spell_name` (`ID`, `Name`, `VerifiedBuild`) VALUES (1900003, 'Windrunner\'s Grace', 66263);
REPLACE INTO `hotfixes`.`hotfix_data` (`Id`, `UniqueId`, `TableHash`, `RecordId`, `Status`, `VerifiedBuild`) VALUES (1900003, 190000300, 1187407512, 1900003, 1, 66263);

-- spell
REPLACE INTO `hotfixes`.`spell` (`ID`, `NameSubtext`, `Description`, `AuraDescription`, `VerifiedBuild`) VALUES (1900003, NULL, 'Increases movement speed and mounted speed by 100%%.', 'Movement speed and mounted speed increased by 100%%.', 66263);
REPLACE INTO `hotfixes`.`hotfix_data` (`Id`, `UniqueId`, `TableHash`, `RecordId`, `Status`, `VerifiedBuild`) VALUES (1900004, 190000401, 3776013982, 1900003, 1, 66263);

-- spell_misc
REPLACE INTO `hotfixes`.`spell_misc` (`ID`, `Attributes1`, `Attributes2`, `Attributes3`, `Attributes4`, `Attributes5`, `Attributes6`, `Attributes7`, `Attributes8`, `Attributes9`, `Attributes10`, `Attributes11`, `Attributes12`, `Attributes13`, `Attributes14`, `Attributes15`, `Attributes16`, `Attributes17`, `DifficultyID`, `CastingTimeIndex`, `DurationIndex`, `PvPDurationIndex`, `RangeIndex`, `SchoolMask`, `Speed`, `LaunchDelay`, `MinDuration`, `SpellIconFileDataID`, `ActiveIconFileDataID`, `ContentTuningID`, `ShowFutureSpellPlayerConditionID`, `SpellVisualScript`, `ActiveSpellVisualScript`, `SpellID`, `VerifiedBuild`) VALUES (1900003, 268436480, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 21, 0, 1, 8, 0.0, 0.0, 0.0, 136116, 0, 0, 0, 0, 0, 1900003, 66263);
REPLACE INTO `hotfixes`.`hotfix_data` (`Id`, `UniqueId`, `TableHash`, `RecordId`, `Status`, `VerifiedBuild`) VALUES (1900005, 190000502, 3322146344, 1900003, 1, 66263);

-- spell_effect (index 0) — +100% movement speed
REPLACE INTO `hotfixes`.`spell_effect` (`ID`, `EffectAura`, `DifficultyID`, `EffectIndex`, `Effect`, `EffectAmplitude`, `EffectAttributes`, `EffectAuraPeriod`, `EffectBonusCoefficient`, `EffectChainAmplitude`, `EffectChainTargets`, `EffectItemType`, `EffectMechanic`, `EffectPointsPerResource`, `EffectPosFacing`, `EffectRealPointsPerLevel`, `EffectTriggerSpell`, `BonusCoefficientFromAP`, `PvpMultiplier`, `Coefficient`, `Variance`, `ResourceCoefficient`, `GroupSizeBasePointsCoefficient`, `EffectBasePoints`, `ScalingClass`, `TargetNodeGraph`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectSpellClassMask1`, `EffectSpellClassMask2`, `EffectSpellClassMask3`, `EffectSpellClassMask4`, `ImplicitTarget1`, `ImplicitTarget2`, `SpellID`, `VerifiedBuild`) VALUES (1900003, 31, 0, 0, 6, 0.0, 0, 0, 0.0, 1.0, 0, 0, 0, 0.0, 0, 0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1900003, 66263);
REPLACE INTO `hotfixes`.`hotfix_data` (`Id`, `UniqueId`, `TableHash`, `RecordId`, `Status`, `VerifiedBuild`) VALUES (1900006, 190000603, 4030871717, 1900003, 1, 66263);

-- spell_effect (index 1) — +100% mounted speed
REPLACE INTO `hotfixes`.`spell_effect` (`ID`, `EffectAura`, `DifficultyID`, `EffectIndex`, `Effect`, `EffectAmplitude`, `EffectAttributes`, `EffectAuraPeriod`, `EffectBonusCoefficient`, `EffectChainAmplitude`, `EffectChainTargets`, `EffectItemType`, `EffectMechanic`, `EffectPointsPerResource`, `EffectPosFacing`, `EffectRealPointsPerLevel`, `EffectTriggerSpell`, `BonusCoefficientFromAP`, `PvpMultiplier`, `Coefficient`, `Variance`, `ResourceCoefficient`, `GroupSizeBasePointsCoefficient`, `EffectBasePoints`, `ScalingClass`, `TargetNodeGraph`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectSpellClassMask1`, `EffectSpellClassMask2`, `EffectSpellClassMask3`, `EffectSpellClassMask4`, `ImplicitTarget1`, `ImplicitTarget2`, `SpellID`, `VerifiedBuild`) VALUES (1900004, 32, 0, 1, 6, 0.0, 0, 0, 0.0, 1.0, 0, 0, 0, 0.0, 0, 0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1900003, 66263);
REPLACE INTO `hotfixes`.`hotfix_data` (`Id`, `UniqueId`, `TableHash`, `RecordId`, `Status`, `VerifiedBuild`) VALUES (1900007, 190000704, 4030871717, 1900004, 1, 66263);
