-- ============================================================
-- Spell: Chronal Surge (ID: 1900004)
-- +250% all haste (melee, ranged, spell, cooldowns)
-- Generated by VoxCore Spell Creator
-- ============================================================

-- spell_name
REPLACE INTO `hotfixes`.`spell_name` (`ID`, `Name`, `VerifiedBuild`) VALUES (1900004, 'Chronal Surge', 66263);
REPLACE INTO `hotfixes`.`hotfix_data` (`Id`, `UniqueId`, `TableHash`, `RecordId`, `Status`, `VerifiedBuild`) VALUES (1900010, 190001000, 1187407512, 1900004, 1, 66263);

-- spell
REPLACE INTO `hotfixes`.`spell` (`ID`, `NameSubtext`, `Description`, `AuraDescription`, `VerifiedBuild`) VALUES (1900004, NULL, 'Increases melee, ranged, and spell haste by 250%.', 'All haste increased by 250%.', 66263);
REPLACE INTO `hotfixes`.`hotfix_data` (`Id`, `UniqueId`, `TableHash`, `RecordId`, `Status`, `VerifiedBuild`) VALUES (1900011, 190001101, 3776013982, 1900004, 1, 66263);

-- spell_misc
REPLACE INTO `hotfixes`.`spell_misc` (`ID`, `Attributes1`, `Attributes2`, `Attributes3`, `Attributes4`, `Attributes5`, `Attributes6`, `Attributes7`, `Attributes8`, `Attributes9`, `Attributes10`, `Attributes11`, `Attributes12`, `Attributes13`, `Attributes14`, `Attributes15`, `Attributes16`, `Attributes17`, `DifficultyID`, `CastingTimeIndex`, `DurationIndex`, `PvPDurationIndex`, `RangeIndex`, `SchoolMask`, `Speed`, `LaunchDelay`, `MinDuration`, `SpellIconFileDataID`, `ActiveIconFileDataID`, `ContentTuningID`, `ShowFutureSpellPlayerConditionID`, `SpellVisualScript`, `ActiveSpellVisualScript`, `SpellID`, `VerifiedBuild`) VALUES (1900004, 268436480, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 21, 0, 1, 64, 0.0, 0.0, 0.0, 136048, 0, 0, 0, 0, 0, 1900004, 66263);
REPLACE INTO `hotfixes`.`hotfix_data` (`Id`, `UniqueId`, `TableHash`, `RecordId`, `Status`, `VerifiedBuild`) VALUES (1900012, 190001202, 3322146344, 1900004, 1, 66263);

-- spell_effect (index 0) — +250% melee & ranged haste
REPLACE INTO `hotfixes`.`spell_effect` (`ID`, `EffectAura`, `DifficultyID`, `EffectIndex`, `Effect`, `EffectAmplitude`, `EffectAttributes`, `EffectAuraPeriod`, `EffectBonusCoefficient`, `EffectChainAmplitude`, `EffectChainTargets`, `EffectItemType`, `EffectMechanic`, `EffectPointsPerResource`, `EffectPosFacing`, `EffectRealPointsPerLevel`, `EffectTriggerSpell`, `BonusCoefficientFromAP`, `PvpMultiplier`, `Coefficient`, `Variance`, `ResourceCoefficient`, `GroupSizeBasePointsCoefficient`, `EffectBasePoints`, `ScalingClass`, `TargetNodeGraph`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectSpellClassMask1`, `EffectSpellClassMask2`, `EffectSpellClassMask3`, `EffectSpellClassMask4`, `ImplicitTarget1`, `ImplicitTarget2`, `SpellID`, `VerifiedBuild`) VALUES (1900010, 192, 0, 0, 6, 0.0, 0, 0, 0.0, 1.0, 0, 0, 0, 0.0, 0, 0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 250, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1900004, 66263);
REPLACE INTO `hotfixes`.`hotfix_data` (`Id`, `UniqueId`, `TableHash`, `RecordId`, `Status`, `VerifiedBuild`) VALUES (1900013, 190001303, 4030871717, 1900010, 1, 66263);

-- spell_effect (index 1) — +250% spell casting speed
REPLACE INTO `hotfixes`.`spell_effect` (`ID`, `EffectAura`, `DifficultyID`, `EffectIndex`, `Effect`, `EffectAmplitude`, `EffectAttributes`, `EffectAuraPeriod`, `EffectBonusCoefficient`, `EffectChainAmplitude`, `EffectChainTargets`, `EffectItemType`, `EffectMechanic`, `EffectPointsPerResource`, `EffectPosFacing`, `EffectRealPointsPerLevel`, `EffectTriggerSpell`, `BonusCoefficientFromAP`, `PvpMultiplier`, `Coefficient`, `Variance`, `ResourceCoefficient`, `GroupSizeBasePointsCoefficient`, `EffectBasePoints`, `ScalingClass`, `TargetNodeGraph`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectSpellClassMask1`, `EffectSpellClassMask2`, `EffectSpellClassMask3`, `EffectSpellClassMask4`, `ImplicitTarget1`, `ImplicitTarget2`, `SpellID`, `VerifiedBuild`) VALUES (1900011, 65, 0, 1, 6, 0.0, 0, 0, 0.0, 1.0, 0, 0, 0, 0.0, 0, 0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 250, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1900004, 66263);
REPLACE INTO `hotfixes`.`hotfix_data` (`Id`, `UniqueId`, `TableHash`, `RecordId`, `Status`, `VerifiedBuild`) VALUES (1900014, 190001404, 4030871717, 1900011, 1, 66263);

-- spell_effect (index 2) — +250% cooldown recovery by haste
REPLACE INTO `hotfixes`.`spell_effect` (`ID`, `EffectAura`, `DifficultyID`, `EffectIndex`, `Effect`, `EffectAmplitude`, `EffectAttributes`, `EffectAuraPeriod`, `EffectBonusCoefficient`, `EffectChainAmplitude`, `EffectChainTargets`, `EffectItemType`, `EffectMechanic`, `EffectPointsPerResource`, `EffectPosFacing`, `EffectRealPointsPerLevel`, `EffectTriggerSpell`, `BonusCoefficientFromAP`, `PvpMultiplier`, `Coefficient`, `Variance`, `ResourceCoefficient`, `GroupSizeBasePointsCoefficient`, `EffectBasePoints`, `ScalingClass`, `TargetNodeGraph`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectSpellClassMask1`, `EffectSpellClassMask2`, `EffectSpellClassMask3`, `EffectSpellClassMask4`, `ImplicitTarget1`, `ImplicitTarget2`, `SpellID`, `VerifiedBuild`) VALUES (1900012, 347, 0, 2, 6, 0.0, 0, 0, 0.0, 1.0, 0, 0, 0, 0.0, 0, 0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 250, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1900004, 66263);
REPLACE INTO `hotfixes`.`hotfix_data` (`Id`, `UniqueId`, `TableHash`, `RecordId`, `Status`, `VerifiedBuild`) VALUES (1900015, 190001505, 4030871717, 1900012, 1, 66263);
